import { useMemo, useState } from "react";
import { courses, fields, updates, type Resource } from "./curriculum";

function ResourceRow({resource,index}:{resource:Resource;index:number}){return <a className="resource" href={`https://www.youtube.com/watch?v=${resource.id}`} target="_blank" rel="noreferrer"><span className="resource-index">{String(index+1).padStart(2,"0")}</span><span className="resource-copy">{resource.fresh&&<small className="new-line">NEW IN AUGUST</small>}<strong>{resource.title}</strong><span>{resource.speaker}</span><p>{resource.note}</p></span><span className="resource-meta"><span>{resource.format}</span><span aria-label={`Approximately ${resource.length}`}>≈ {resource.length}</span><b aria-hidden="true">↗</b></span></a>}

export default function Home(){
const[activeCourse,setActiveCourse]=useState("01");const[activeField,setActiveField]=useState("agents");const[format,setFormat]=useState<"All"|"Talk"|"Workshop">("All");
const course=useMemo(()=>courses.find(item=>item.id===activeCourse)??courses[0],[activeCourse]);const field=useMemo(()=>fields.find(item=>item.id===activeField)??fields[0],[activeField]);const visibleResources=course.resources.filter(item=>format==="All"||item.format===format);
return <main id="top">
<div className="update-strip"><span>CURRICULUM UPDATE</span><p>Reviewed through August 24, 2026</p><a href="#updates">See what changed ↓</a></div>
<header><a className="brand" href="#top"><span>AI·E</span><b>Open Curriculum</b></a><nav aria-label="Primary navigation"><a href="#path">Learning path</a><a href="#fields">Subfields</a><a href="#updates">New picks</a><a href="#method">Method</a></nav></header>
<section className="hero"><div className="hero-copy"><p className="kicker">A field guide for people who build</p><h1>Learn AI engineering<br/><em>as a connected discipline.</em></h1><p className="hero-deck">The strongest talks from the AI Engineer archive, arranged by what you need to understand first and where you may want to specialize next.</p><div className="hero-actions"><a href="#path">Start with the core <span>↓</span></a><a href="#fields">Choose a subfield <span>→</span></a></div></div><div className="orientation" aria-label="Curriculum orientation"><div className="orientation-head"><span>YOUR ROUTE</span><b>FOUNDATION → DEPTH</b></div><ol>{courses.map(item=><li key={item.id}><button onClick={()=>{setActiveCourse(item.id);document.querySelector("#path")?.scrollIntoView({behavior:"smooth"})}}><span>{item.id}</span><b>{item.title}</b><i style={{background:item.accent}}/></button></li>)}</ol><p>Take all six in order, or enter where your current mental model becomes uncertain.</p></div></section>
<section className="summary-band" aria-label="Curriculum summary"><p><strong>06</strong><span>core courses</span></p><p><strong>06</strong><span>subfields</span></p><p><strong>{new Set([...courses, ...fields].flatMap(item => item.resources.map(resource => resource.id))).size}</strong><span>guided resources</span></p><p><strong>5</strong><span>August 2026 updates</span></p></section>
<section className="path" id="path"><div className="section-heading"><p className="kicker">Part one · The common core</p><h2>Build the mental model<br/>before the tool stack.</h2><p>Each course states what to know before you begin, what you should be able to do afterward, and why every selected resource earns your attention.</p></div><div className="course-shell"><aside aria-label="Core courses"><div className="aside-title"><span>COURSE MAP</span><b>01–06</b></div>{courses.map(item=><button key={item.id} className={item.id===activeCourse?"active":""} onClick={()=>setActiveCourse(item.id)}><span>{item.id}</span><b>{item.title}</b><i style={{background:item.accent}}/></button>)}</aside><article className="course-panel" key={course.id}><div className="course-overview" style={{borderTopColor:course.accent}}><div className="course-label"><span>COURSE {course.id}</span><b>FOUNDATION</b></div><h3>{course.title}</h3><p>{course.summary}</p><dl><div><dt>Before you begin</dt><dd>{course.prerequisite}</dd></div><div><dt>After this course</dt><dd>{course.outcome}</dd></div></dl></div><div className="resource-toolbar"><div><span>ESSENTIAL SEQUENCE</span><b>{visibleResources.length} resources</b></div><div className="filters" aria-label="Filter by format">{(["All","Talk","Workshop"] as const).map(item=><button key={item} className={item===format?"selected":""} onClick={()=>setFormat(item)}>{item}</button>)}</div></div><div>{visibleResources.map((item,index)=><ResourceRow key={item.id} resource={item} index={index}/>)}</div></article></div></section>
<section className="fields" id="fields"><div className="section-heading"><p className="kicker">Part two · Choose your depth</p><h2>A subfield is a question<br/>you keep returning to.</h2><p>The core gives you shared foundations. Choose one direction for deeper study, then prove your understanding through a real project.</p></div><div className="field-grid" role="tablist" aria-label="AI engineering subfields">{fields.map((item,index)=><button key={item.id} role="tab" aria-selected={item.id===activeField} onClick={()=>setActiveField(item.id)}><span>{String(index+1).padStart(2,"0")}</span><b>{item.title}</b><i>→</i></button>)}</div><article className="field-panel" key={field.id}><div className="field-intro"><span>THE GUIDING QUESTION</span><h3>{field.question}</h3><p>{field.description}</p><div className="capstone"><b>CAPSTONE DIRECTION</b><p>{field.project}</p></div></div><div className="field-resources"><div className="field-list-title"><span>STRONG STARTING SET</span><b>{field.resources.length} selections</b></div>{field.resources.map((item,index)=><ResourceRow key={item.id} resource={item} index={index}/>)}</div></article></section>
<section className="updates" id="updates"><div className="updates-intro"><p className="kicker">August 2026 review</p><h2>What changed,<br/>and why.</h2><p>The archive is growing quickly. New does not automatically mean better. These five selections added a distinct mental model, stronger evidence, or a clearer production case.</p></div><div className="update-list">{updates.map(item=><a key={item.resource.id} href={`https://www.youtube.com/watch?v=${item.resource.id}`} target="_blank" rel="noreferrer"><span className="update-date">{item.date}</span><span className="update-action">{item.action}<small>{item.place}</small></span><span className="update-copy"><b>{item.resource.title}</b><p>{item.resource.note}</p></span><i>↗</i></a>)}</div></section>
<section className="method" id="method"><div><p className="kicker">How the list is made</p><h2>A curriculum,<br/>not a feed.</h2></div><div className="method-copy"><p>Conference archives follow events. Learning follows dependencies. We inspect the content, compare overlapping explanations, and keep only resources that earn their place.</p><div className="criteria"><div><b>01 · CLARITY</b><span>Does it teach a useful mental model?</span></div><div><b>02 · DEPTH</b><span>Does it reward focused attention?</span></div><div><b>03 · DURABILITY</b><span>Will the lesson outlast one product cycle?</span></div><div><b>04 · PRACTICE</b><span>Can a learner apply it to a real system?</span></div></div></div></section>
<footer><div><b>AI·E</b><span>Open Curriculum</span></div><p>Independently curated from the AI Engineer video archive. Not affiliated with or accredited by AI Engineer.</p><a href="#top">Back to top ↑</a></footer>
</main>}
