export type Resource = { title:string; speaker:string; length:string; format:"Talk"|"Workshop"; id:string; note:string; fresh?:boolean };
type Course = { id:string; title:string; summary:string; prerequisite:string; outcome:string; accent:string; resources:Resource[] };
type Field = { id:string; title:string; question:string; description:string; project:string; resources:Resource[] };
const video=(title:string,speaker:string,length:string,format:"Talk"|"Workshop",id:string,note:string,fresh=false):Resource=>({title,speaker,length,format,id,note,fresh});

const contextWorkshop=video("Context Engineering in 2026: Compaction, Memory & Cost","Louis-François Bouchard, Omar Solano, Samridhi Vaid","1h 03m","Workshop","WP3hjUXd918","An unusually useful experiment-led workshop on context rot, caching, compaction, memory, latency, and cost.",true);
const securityFirewall=video("Security Firewall for Agents","Ryan Dahl, Deno","19m","Talk","MkRYPFIMCSA","A concrete argument for putting policy, credentials, and approvals outside the agent as an independent security boundary.",true);
const uberSdlc=video("Building Blocks for Uber’s Software Factory","Uday Kiran Medisetty and Adam Huda, Uber","18m","Talk","17-YSUHo6Lk","A rare production-scale view of gateways, identity, context graphs, remote environments, validation, and agent-driven delivery.",true);
const compoundEngineering=video("The Era of Compound Engineering","Kieran Klaassen, Every/Cora","21m","Talk","_ehJyfHg1Vk","A durable workflow: turn corrections, judgment, and repeated instructions into capabilities that improve the next run.",true);
const designTaste=video("The Missing Layer: Design Taste in AI Agents","Hassan El Mghari, Together AI","14m","Talk","7GMKdpLsxwU","A practical case for references, explicit design constraints, persistent preferences, and human-led iteration.",true);

export const courses:Course[]=[
{id:"01",title:"Systems before agents",accent:"#ef725d",prerequisite:"You can build a web application or API.",outcome:"Map an AI product, find its likely failure points, and choose a small first architecture.",summary:"Learn the recurring parts of an AI product: model calls, structured outputs, context, tools, feedback, and the application around them.",resources:[video("AI Engineering 101","AI Engineer workshop","3h 02m","Workshop","C0ZUdFg-iTo","A broad orientation. Watch for the map, then revisit individual sections."),video("Building Blocks for LLM Systems and Products","Eugene Yan","17m","Talk","LzeC1AQ-U5o","A compact vocabulary for the components behind useful LLM applications."),video("AI System Design: From Idea to Production","Apoorva Joshi","29m","Talk","T0HhO4YtTfE","Connects product intent to architecture, data, evaluation, and operations.")]},
{id:"02",title:"Context and retrieval",accent:"#e6ae2d",prerequisite:"Course 01 and basic database concepts.",outcome:"Design and evaluate retrieval, then choose between search, long context, memory, and structured data.",summary:"Build the information layer that lets a model work with private, changing, or precise knowledge without placing everything in one prompt.",resources:[video("Information Retrieval from the Ground Up","Philipp Krenn","1h 48m","Workshop","4Xe_iMYxBQc","The durable foundation: ranking, lexical search, vectors, and measurement."),video("RAG Agents in Production: 10 Lessons We Learned","Douwe Kiela","17m","Talk","kPL-6-9MVyA","Production lessons from the researcher who introduced RAG."),video("Why More Context Makes Your Agent Dumber","Nupur Sharma","26m","Talk","EcqMYoIV57A","A counterweight to solving every problem with a larger context window."),contextWorkshop]},
{id:"03",title:"Agents, tools, and skills",accent:"#43a479",prerequisite:"Courses 01 and 02.",outcome:"Choose between a workflow and an agent, define useful tools, and keep the loop understandable.",summary:"Move from one model response to systems that choose actions, use tools, manage state, and complete bounded work.",resources:[video("How We Build Effective Agents","Barry Zhang, Anthropic","15m","Talk","D7_ipDqhtwk","A clear introduction to simple, composable agent patterns."),video("12-Factor Agents","Dex Horthy","17m","Talk","8kMaTybvDUw","Patterns for keeping agent behavior explicit, testable, and recoverable."),video("Do Not Build Agents, Build Skills Instead","Barry Zhang and Mahesh Murag, Anthropic","16m","Talk","CEvIs9y1uog","Shows when reusable capabilities beat a larger agent graph."),video("Building Agents with Model Context Protocol","Mahesh Murag, Anthropic","1h 44m","Workshop","kQmXtrmQ5Zg","A hands-on path from tool boundaries to an interoperable integration.")]},
{id:"04",title:"Evaluation as engineering",accent:"#4275d9",prerequisite:"A working AI feature or prototype.",outcome:"Build an evaluation set, choose graders, inspect traces, and avoid misleading scores.",summary:"Treat quality as something you define, measure, inspect, and improve continuously, not a demo-time impression.",resources:[video("Why Should Anyone Care About Evals?","Manu Goyal","6m","Talk","jJ45Yz1lJao","A six-minute orientation that gives the subject a clear purpose."),video("Evals 101","Doug Guthrie, Braintrust","49m","Workshop","bk0TmxoZlUY","A grounded introduction to datasets, scorers, experiments, and feedback loops."),video("Building and Evaluating AI Agents","Sayash Kapoor","20m","Talk","d5EltXhbcfA","A skeptical research view of what agent benchmarks reveal and hide."),video("Five Hard-Earned Lessons About Evals","Ankur Goyal","20m","Talk","a4BV0gGmXgA","Production lessons on where evaluation programs stall.")]},
{id:"05",title:"Production and reliability",accent:"#8a63bb",prerequisite:"Courses 03 and 04.",outcome:"Turn a prototype into an operable service with explicit failure and recovery paths.",summary:"Design for long-running work, retries, state, observation, cost, human intervention, and realities beyond the prototype.",resources:[video("The Agent Development Life Cycle","Zack Reneau-Wedeen, Sierra","19m","Talk","0vBKv9yAQi4","An end-to-end frame for iteration, release, and production learning."),video("Scaling AI Agents Without Breaking Reliability","Preeti Somal, Temporal","15m","Talk","1izYWsokr9s","Introduces durable execution concerns that request-response code misses."),video("Building Durable, Production-Ready Agents","OpenAI and Temporal","1h 19m","Workshop","k8cnVCMYmNc","A practical implementation of persistence, retries, and resumability."),uberSdlc]},
{id:"06",title:"Security and trust",accent:"#dc5368",prerequisite:"Course 03 and familiarity with web security.",outcome:"Threat-model tools, identity, data access, code execution, network egress, and approval boundaries.",summary:"Give capable systems the least authority they need, isolate untrusted content, and make important actions reviewable.",resources:[video("OpenAI on Securing Code-Executing AI Agents","Fouad Matin, OpenAI","14m","Talk","w7IMuYsBNr8","A focused look at sandboxing and the attack surface of code execution."),video("How to Secure Agents Using OAuth","Jared Hanson","19m","Talk","blmAkayzE8M","Clarifies delegated access, scopes, consent, and machine identity."),video("Your Insecure MCP Server Will Not Survive Production","Tun Shwe","25m","Talk","BurJvbqFr4c","A concrete tour of insecure defaults in tool servers."),securityFirewall]}
];

export const fields:Field[]=[
{id:"agents",title:"Agent engineering",question:"How do systems act for longer without becoming harder to understand?",description:"Go deeper on harnesses, memory, planning, durable execution, and human oversight.",project:"Build a research agent that can pause, recover, show its work, and pass a task-level evaluation suite.",resources:[video("Build Agents That Run for Hours","Anthropic workshop","1h 16m","Workshop","mR-WAvEPRwE","A full build focused on long-horizon work."),video("Architecting Agent Memory","Richmond Alake","18m","Talk","W2HVdB4Jbjs","Separates memory patterns from context accumulation."),video("From Stateless Nightmares to Durable Agents","Samuel Colvin","22m","Talk","flf_IKnFYnE","Makes persistence and recovery concrete.")]},
{id:"coding",title:"Coding agents",question:"What changes when software becomes the environment an agent works inside?",description:"Study repositories as context, harness design, verification, sandboxes, and the new division of labor between people and agents.",project:"Prepare a real repository for agents, then measure improvement on a set of maintenance tasks.",resources:[video("Claude Code and the Evolution of Agentic Coding","Boris Cherny, Anthropic","18m","Talk","Lue8K2jqfKk","A view from the creator of a leading coding agent."),video("Harness Engineering","Ryan Lopopolo, OpenAI","46m","Talk","am_oeAoUhew","Explains the system around the model when agents execute and people steer."),video("Making Codebases Agent Ready","Eno Reyes, Factory","16m","Talk","ShuJ_CN6zr4","Turns repository preparation into specific engineering work."),compoundEngineering]},
{id:"knowledge",title:"Knowledge systems",question:"How should an AI system find, organize, and justify what it knows?",description:"Advance from basic retrieval into hybrid search, graphs, memory, and decision-aware context.",project:"Create a retrieval system with failure categories, cited answers, and a measured improvement loop.",resources:[video("Building Production-Ready RAG Applications","Jerry Liu","19m","Talk","TRjq7t2Ms5I","A proven production-oriented overview."),video("RAG in 2025: State of the Art","Tengyu Ma","19m","Talk","W_CYk2ogcDI","A research-grounded update after the basics."),video("GraphRAG: Knowledge Graphs Meet RAG","Emil Eifrem","19m","Talk","knDDGYHnnSI","A clear case for adding explicit relationships.")]},
{id:"models",title:"Inference and models",question:"How do you choose and serve the intelligence beneath the application?",description:"Learn serving, latency, throughput, post-training, smaller models, and the economics of model choice.",project:"Benchmark two serving stacks and three models against quality, latency, and cost targets.",resources:[video("AI Engineering 201: Inference","AI Engineer workshop","1h 43m","Workshop","N7lJY5IKVLE","A broad foundation for the serving layer."),video("Introduction to LLM Serving with SGLang","Philip Kiely and Yineng Zhang","44m","Workshop","Ahtaha9fEM0","A concrete implementation after the overview."),video("Modern Post-Training: A Deep Dive","Will Brown","47m","Talk","V-EDrhIhHzQ","A current map of how behavior is shaped after pretraining.")]},
{id:"interfaces",title:"Multimodal and interface design",question:"What should an AI product feel like when chat is not enough?",description:"Explore voice, generative interfaces, visual understanding, interruption, and interaction patterns suited to agentic work.",project:"Build a voice or visual assistant that exposes state, handles interruption, and gives users a clear correction path.",resources:[video("Building Multimodal AI Agents From Scratch","Apoorva Joshi","37m","Talk","640KMYtxCeI","A technical bridge from text-only systems."),video("Building Effective Voice Agents","Toki Sherbakov and Anoop Kotha, OpenAI","17m","Talk","-OXiljTJxQU","A focused overview of the voice stack."),video("Designing Generative UI for MCP Apps","Ruben Casas, Postman","17m","Talk","hCMrEfPG2Yg","Moves beyond text without hiding control."),designTaste]},
{id:"reliability",title:"Evals and reliable AI",question:"How do you know the system improved rather than merely changed?",description:"Go deeper on domain evaluation, judges, simulation, production traces, and the limits of benchmark thinking.",project:"Build an evaluation program from real failures, with independent graders and release criteria.",resources:[video("Domain-Specific LLM Evaluation Systems","Hamel Husain and Emil Sedgh","19m","Talk","eLXF0VojuSs","Makes evaluation reflect the actual use case."),video("Ship Real Agents: Hands-On Evals","Laurie Voss, Arize","2h 04m","Workshop","Xfl50508LZM","The practical session for building the complete loop."),video("Do Not Ship Skills Without Evals","Philipp Schmid, Google DeepMind","22m","Talk","0vphxNt4wyk","Connects reusable capabilities to evidence of reliability.")]}
];

export const updates=[{date:"AUG 17",action:"Added",resource:securityFirewall,place:"Security and trust"},{date:"AUG 17",action:"Replaced",resource:contextWorkshop,place:"Context and retrieval"},{date:"AUG 19",action:"Added",resource:compoundEngineering,place:"Coding agents"},{date:"AUG 21",action:"Replaced",resource:uberSdlc,place:"Production and reliability"},{date:"AUG 22",action:"Added",resource:designTaste,place:"Multimodal and interface design"}];

